/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banksystem1;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TH3_HACK3R
 */
public class Deposit extends javax.swing.JDialog {

    private Account account=null;
    private int AccNum;
    /**
     * Creates new form Deposit
     */
    public Deposit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setSize(409 , 100);
    }
    public Deposit(java.awt.Frame parent, boolean modal,int AccNum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setSize(409 , 100);
        this.AccNum=AccNum;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DValueTxt = new javax.swing.JTextField();
        Deposit = new javax.swing.JButton();
        DCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposit");
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel1.setText("Value");
        getContentPane().add(jLabel1);
        getContentPane().add(DValueTxt);

        Deposit.setText("Deposit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });
        getContentPane().add(Deposit);

        DCancel.setText("Cancel");
        DCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCancelActionPerformed(evt);
            }
        });
        getContentPane().add(DCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:
        Double Value,Test;
        if(DValueTxt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Value cannot be empty", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // lazem 2t2ked enha m4 string 34an m4 hy3rf y7wlha

        else
        {
            try
            {
                Test=Double.parseDouble(DValueTxt.getText());
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(this, "Value must be a number", "ERROR!!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        if(Double.parseDouble(DValueTxt.getText())<=0)
        {
            JOptionPane.showMessageDialog(this, "Value cannot equal to 0 or negative value", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Value=Double.parseDouble(DValueTxt.getText());
        JOptionPane.showMessageDialog(this, "Diposit value = "+ Value);
        
        ArrayList accounts;
        try {
            accounts = Account.load2();
            account = (Account)accounts.get(AccNum-1);
            account.deposit(Value);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       this.dispose();
    }//GEN-LAST:event_DepositActionPerformed

    private void DCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_DCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Deposit dialog = new Deposit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DCancel;
    private javax.swing.JTextField DValueTxt;
    private javax.swing.JButton Deposit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

public Account getAcc()
    {
        return this.account;
    }
}
